name: Continuous Integration

on:
  workflow_dispatch:
  push:
    paths:
      - '**.c'
      - '**.h'
      - '**.cpp'
      - '**.hpp'
      - '**.build'
      - '**.in'
      - '**.yml'
      - '**.gradle'
      - CMakeLists.txt
  pull_request:
    paths:
      - '**.c'
      - '**.h'
      - '**.cpp'
      - '**.hpp'
      - '**.build'
      - '**.in'
      - '**.yml'
      - '**.gradle'
      - CMakeLists.txt

env:
  CMAKE_GENERATOR: Ninja
  HOMEBREW_NO_ANALYTICS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_UPGRADE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  build-web:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      EM_VERSION: 3.1.24
      EM_CACHE_FOLDER: emsdk-cache
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libsdl2-dev

      - name: Setup cache
        id: cache-system-libraries
        uses: actions/cache@v2
        with:
          path: ${{ env.EM_CACHE_FOLDER }}
          key: ${{ env.EM_VERSION }}-${{ runner.os }}

      - name: Setup Emscripten SDK
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{ env.EM_VERSION }}
          actions-cache-folder: ${{ env.EM_CACHE_FOLDER }}

      - name: Set up base environment
        run: |
          sudo apt-get install build-essential
          echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

      - name: Set up default build tools
        run: brew install make nasm ninja cmake

      - name: Build project
        run: |
          emcmake cmake -S . -B build
          cmake --build build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: krkrsdl2-web
          path: |
            build/krkrsdl2_repo/krkrsdl2.wasm
            build/krkrsdl2_repo/krkrsdl2.js
            build/krkrsdl2_repo/index.html

  build-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libsdl2-dev

      - name: Set up Homebrew environment
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

      - name: Set up default build tools
        run: brew install make nasm ninja cmake

      - name: Configure project
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: krkrsdl2-ubuntu
          path: build/krkrsdl2_repo/krkrsdl2

  build-win32:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        platform:
          - triplet: i686-w64-mingw32
            cmake-system-compiler: i686

          - triplet: x86_64-w64-mingw32
            cmake-system-compiler: amd64
        compiler: [gcc, clang]

        include:
          - platform:
              triplet: armv7-w64-mingw32
              cmake-system-compiler: arm
            compiler: clang

          - platform:
              triplet: aarch64-w64-mingw32
              cmake-system-compiler: arm64
            compiler: clang
    steps:
      - name: Set up base environment
        run: |
          sudo apt-get install build-essential git
          echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up default build tools
        run: brew install make nasm ninja cmake

      - name: Set up mingw-w64 for GCC
        if: matrix.compiler == 'gcc'
        run: brew install mingw-w64

      - name: Set up mingw-w64 for Clang
        if: matrix.compiler == 'clang'
        run: |
          curl -LO https://github.com/mstorsjo/llvm-mingw/releases/download/20220323/llvm-mingw-20220323-msvcrt-ubuntu-18.04-x86_64.tar.xz
          tar xvf llvm-mingw-20220323-msvcrt-ubuntu-18.04-x86_64.tar.xz
          mv llvm-mingw-20220323-msvcrt-ubuntu-18.04-x86_64 /opt/llvm-mingw
          export PATH="/opt/llvm-mingw/bin:$PATH"
          echo "/opt/llvm-mingw/bin" >> $GITHUB_PATH

      - name: Configure project
        run: >-
          cmake -S . -B build -GNinja -DCMAKE_SYSTEM_NAME=Windows
          -DCMAKE_SYSTEM_PROCESSOR=${{ matrix.platform.cmake-system-compiler }}
          -DCMAKE_FIND_ROOT_PATH=/dev/null
          -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER
          -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY
          -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY
          -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ONLY
          -DCMAKE_C_COMPILER=${{ matrix.platform.triplet }}-gcc
          -DCMAKE_CXX_COMPILER=${{ matrix.platform.triplet }}-g++
          -DCMAKE_RC_COMPILER=${{ matrix.platform.triplet }}-windres
          -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build

      - name: Archive artifact
        run: |
          cd build 
          7z a -tzip krkrsdl2-win32-${{ matrix.platform.cmake-system-compiler }}-${{ matrix.platform.compiler }}.zip *.exe

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: krkrsdl2-win32-${{ matrix.platform.cmake-system-compiler }}-${{ matrix.compiler }}
          path: build/*.zip

  build-vita:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    container:
      image: vitasdk/vitasdk:latest
    steps:
      - name: Install dependencies
        run: |
          apk update
          apk add cmake make ninja git curl

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download krkrsdl2-kag3-demo build
        run: curl -LOC - https://github.com/krkrsdl2/krkrsdl2-kag3-demo/releases/download/latest/data.xp3

      - name: Build project
        run: |
          cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=${VITASDK}/share/vita.toolchain.cmake -DEMBED_DATA_PATH=data.xp3
          cmake --build build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: krkrsdl2-vita
          path: build/krkrsdl2_repo/krkrsdl2.vpk

  build-switch:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    container:
      image: devkitpro/devkita64:latest
    steps:
      - name: Install dependencies
        run: |
          apt-get -y update
          apt-get -y install cmake make ninja-build git curl

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download krkrsdl2-kag3-demo build
        run: curl -LOC - https://github.com/krkrsdl2/krkrsdl2-kag3-demo/releases/download/latest/data.xp3

      - name: Build project
        run: |
          cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=${DEVKITPRO}/cmake/Switch.cmake -DEMBED_DATA_PATH=data.xp3
          cmake --build build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: krkrsdl2-switch
          path: build/krkrsdl2_repo/krkrsdl2.nro

  build-darwin-cmake:
    runs-on: macos-14
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        appbundle:
          - platform: MacOS
            enabled: false
            cmake-flags: -DOPTION_BUILD_MACOS_BUNDLE=OFF
            artifact-name: krkrsdl2-macos
            artifact-path: build/krkrsdl2_repo/krkrsdl2

          - platform: MacOS
            enabled: true
            cmake-flags: -DOPTION_BUILD_MACOS_BUNDLE=ON -DEMBED_DATA_PATH=data.xp3
            bundle-path: build/krkrsdl2_repo/krkrsdl2.app
            artifact-name: krkrsdl2-macos-appbundle
            artifact-path: build/krkrsdl2_repo/krkrsdl2-macos-appbundle.zip

          - platform: iOS
            enabled: true
            cmake-flags: -GXcode -DCMAKE_SYSTEM_NAME=iOS -DEMBED_DATA_PATH=data.xp3
            bundle-path: build/krkrsdl2_repo/Debug-iphoneos/krkrsdl2.app
            artifact-name: krkrsdl2-ios-appbundle
            artifact-path: build/krkrsdl2_repo/krkrsdl2-ios-appbundle.zip
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download krkrsdl2-kag3-demo build
        if: matrix.appbundle.enabled == true
        run: curl -LOC - https://github.com/krkrsdl2/krkrsdl2-kag3-demo/releases/download/latest/data.xp3

      - name: Set up default build tools
        run: brew install make nasm ninja cmake

      - name: Build project
        run: |
          cmake -S . -B build ${{ matrix.appbundle.cmake-flags }}
          cmake --build build

      - name: Create app bundle
        run: ditto -ck --rsrc --sequesterRsrc --keepParent ${{ matrix.appbundle.bundle-path }} ${{ matrix.appbundle.artifact-path }}
        if: matrix.appbundle.enabled == true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.appbundle.artifact-name }}
          path: ${{ matrix.appbundle.artifact-path }}

  create-release:
    needs:
      - build-web
      - build-ubuntu
      - build-win32
      - build-darwin-cmake
      - build-vita
      - build-switch
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Prepare artifacts for release
        run: |
          7z a -tzip krkrsdl2-web.zip krkrsdl2-web/*
          7z a -tzip krkrsdl2-ubuntu.zip krkrsdl2-ubuntu/*
          cp krkrsdl2-vita/krkrsdl2.vpk krkrsdl2.vpk
          cp krkrsdl2-switch/krkrsdl2.nro krkrsdl2.nro
          7z a -tzip krkrsdl2-macos.zip krkrsdl2-macos/*
          cp krkrsdl2-macos-appbundle/krkrsdl2-macos-appbundle.zip krkrsdl2-macos-appbundle.zip
          find . -name 'krkrsdl2-win32-*' -type d | while read -r dir; do
            7z a -tzip "${dir}.zip" "$dir/*"
          done

      - name: Create a draft prerelease
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: true
          files: |
            krkrsdl2-web.zip
            krkrsdl2-ubuntu.zip
            krkrsdl2.vpk
            krkrsdl2.nro
            krkrsdl2-macos.zip
            krkrsdl2-macos-appbundle.zip
            krkrsdl2-ios-appbundle.zip
            krkrsdl2-win32-*.zip
